### ISSUE TITLE
additions needed

### ISSUE THREAD

**Issue by dbrunson** [dbrunson/hpc-novice#1]
Concepts to describe:  
- remote computing  
- scheduler metaphors (e.g. waiting for a table at a restaurant.)  
- HPC etiquette

**Comment by dbrunson** [comment]
I also need to look and see if any of the new things we've added to our new user tutorial should be added to this: https://hpcc.okstate.edu/new-user-tutorial-part-2

**Comment by shwina** [comment]
Great resource!
